app/controllers/hummingbird_survey/show_ifs_controller.rb
app/controllers/hummingbird_survey/survey_items_controller.rb
app/controllers/hummingbird_survey/survey_notes_controller.rb
app/controllers/hummingbird_survey/survey_pages_controller.rb
app/controllers/hummingbird_survey/survey_questions_controller.rb
app/controllers/hummingbird_survey/survey_sections_controller.rb
app/enums/show_if_condition.rb
app/enums/survey_question_type.rb
app/views/staff/show_ifs/_form.html.haml
app/views/staff/show_ifs/_show.html.haml
app/views/staff/show_ifs/edit.html.haml
app/views/staff/show_ifs/show.html.haml
app/views/staff/survey_items/_show.html.haml

https://www.wrike.com/open.htm?id=369790312

Full incorporation

---

app/controllers/hummingbird_survey/survey_questions_controller.rb
app/views/hummingbird_survey/common/survey/_show_request_data.html.haml
app/views/staff/survey_questions/_form.html.haml
app/views/staff/surveys/_form.html.haml
hummingbird_survey.gemspec
lib/generators/hummingbird_survey/active_record_generator.rb
lib/hummingbird_survey.rb
lib/hummingbird_survey/models/page_module.rb
lib/hummingbird_survey/models/question_module.rb
lib/hummingbird_survey/models/survey_module.rb
lib/hummingbird_survey/models/survey_page_form.rb
lib/hummingbird_survey/models/survey_response_module.rb
lib/hummingbird_survey/models/surveyable.rb

https://www.wrike.com/open.htm?id=382566967

linked fields basics

---

app/controllers/hummingbird_survey/surveys_controller.rb
app/views/hummingbird_survey/common/survey/_form.html.haml
app/views/staff/surveys/_form.html.haml
lib/generators/hummingbird_survey/active_record_generator.rb
lib/hummingbird_survey/models/page_module.rb
lib/hummingbird_survey/models/survey_module.rb

https://www.wrike.com/open.htm?id=416540749

allow adding pages before and after for display only

---

app/controllers/hummingbird_survey/survey_questions_controller.rb
app/enums/survey_question_type.rb
app/views/hummingbird_survey/common/survey/_answer_survey_question.html.haml
app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb

https://www.wrike.com/open.htm?id=419691445

Agree-field.

---

app/controllers/hummingbird_survey/survey_questions_controller.rb
app/enums/survey_question_type.rb
app/views/hummingbird_survey/common/survey/_answer_survey_question.html.haml
app/views/hummingbird_survey/common/survey/_form.html.haml
app/views/hummingbird_survey/common/survey/_show_question.html.haml
app/views/hummingbird_survey/common/survey/response/_checkbox.html.haml
app/views/hummingbird_survey/common/survey/response/_default.html.haml
app/views/hummingbird_survey/common/survey/response/_encrypted.html.haml
app/views/hummingbird_survey/common/survey/response/_multi_select.html.haml
app/views/hummingbird_survey/common/survey/response/_signature.html.haml
app/views/hummingbird_survey/common/survey/response/_text_area.html.haml
app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb
lib/hummingbird_survey/models/survey_page_form.rb
survey-2c1b9d4a3d5f

https://www.wrike.com/open.htm?id=417896807
Also includes functionality for multi-select.
Todo: Refactor `_show_question.html.haml` into a presenter to present the different question types.

Encrypted field.

---

app/enums/survey_question_type.rb
app/views/hummingbird_survey/common/survey/_answer_survey_question.html.haml
app/views/hummingbird_survey/common/survey/_review_survey.html.haml
app/views/hummingbird_survey/common/survey/_show_question.html.haml
lib/hummingbird_survey/models/question_module.rb

https://www.wrike.com/open.htm?id=414577585
WARNING: Don't merge until after https://github.com/cgratigny/survey/pull/11

Review field

---

app/enums/survey_question_type.rb
app/views/hummingbird_survey/common/survey/_review_survey.html.haml
app/views/staff/survey_questions/_form.html.haml
app/views/staff/survey_questions/_show.html.haml
lib/hummingbird_survey/models/survey_module.rb

https://www.wrike.com/open.htm?id=416520534

Fix country fields

---

lib/hummingbird_survey/models/page_module.rb
lib/hummingbird_survey/models/survey_module.rb

https://www.wrike.com/open.htm?id=421590897

protect against nil pages before/after

---

app/enums/survey_question_type.rb
app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb

https://www.wrike.com/open.htm?id=422254261

more user-friendly way of choosing country field

---

app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb
lib/hummingbird_survey/models/survey_page_form.rb

https://www.wrike.com/open.htm?id=419989608

validate presence of multi-selects

---

app/enums/survey_question_type.rb
app/views/hummingbird_survey/common/survey/_show_question.html.haml
app/views/hummingbird_survey/common/survey/response/_agreement.html.haml

https://www.wrike.com/open.htm?id=423772476

show review as html safe

---

lib/hummingbird_survey/models/show_if_module.rb

https://www.wrike.com/open.htm?id=424415018

fix issues found on dragonfly

---

lib/hummingbird_survey/models/survey_page_form.rb

https://www.wrike.com/open.htm?id=423895611

don't display sub items unless they're displayable

---

app/enums/survey_question_type.rb
lib/hummingbird_survey/models/survey_page_form.rb

https://www.wrike.com/open.htm?id=424395137

validate both checkboxes and agreement fields

---

lib/hummingbird_survey/models/survey_module.rb

https://www.wrike.com/open.htm?id=425566480

allow proper recursion

---

app/views/hummingbird_survey/common/survey/_show_question.html.haml

added in dynamic response type class to aid styling differences for the different type of questions

add response/question type class to responses on review step

---

app/views/hummingbird_survey/common/survey/response/_agreement.html.haml
lib/hummingbird_survey/models/survey_page_form.rb

https://www.wrike.com/open.htm?id=431113672
WARNING: This needs to be released at the same time as https://github.com/cgratigny/dragonfly/pull/3826

store the agree text in the answer options

---

lib/hummingbird_survey/models/item_module.rb
lib/hummingbird_survey/models/page_module.rb
lib/hummingbird_survey/models/question_module.rb
lib/hummingbird_survey/models/question_option_module.rb
lib/hummingbird_survey/models/survey_module.rb

https://www.wrike.com/open.htm?id=442062460

Duplicating quizzes.

---

lib/hummingbird_survey/models/survey_module.rb

https://www.wrike.com/open.htm?id=436153927

DRYer way to sort surveyed data for display

---

app/controllers/hummingbird_survey/survey_response_views_controller.rb
app/views/staff/survey_response_views/_form.html.haml
app/views/staff/survey_response_views/edit.html.haml
app/views/staff/survey_response_views/new.html.haml
app/views/staff/surveys/_form.html.haml
lib/hummingbird_survey.rb
lib/hummingbird_survey/models/survey_module.rb
lib/hummingbird_survey/models/survey_response_view_module.rb

https://www.wrike.com/open.htm?id=460009670

Survey reporting

---

app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb

https://www.wrike.com/open.htm?id=447514986

Add response view labels.

---

app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb
lib/hummingbird_survey/models/survey_page_form.rb

https://www.wrike.com/open.htm?id=466908049

Add validation of not having more than the number of responses.

---

app/enums/survey_question_type.rb
app/views/hummingbird_survey/common/survey/_answer_survey_question.html.haml
app/views/staff/survey_questions/_form.html.haml
lib/hummingbird_survey/models/question_module.rb

https://www.wrike.com/open.htm?id=469097308

add character limits
